In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

Up to, but not including 5

In [5]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

We have broadcasted numbers 0 to 5 as 100

In [10]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[0:5]

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99])

Use a [:] to select everything

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

The slice method effected the original array as well

If you don't want to effect the original array, use this method:

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy[:] = 100

In [19]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Indexing on 2d matrices:

In [21]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

A matrix has been made ^

In [23]:
arr_2d.shape

(3, 3)

Rows and collumns ^

(rows,collumns)

In [24]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[2]

array([35, 40, 45])

In [27]:
arr_2d[1,1]

25

The coordinate value of 25 in the matrix is 1,1

In [29]:
arr_2d[0,2]

15

In [33]:
arr_2d[1:][:1]

array([[20, 25, 30]])

wtf?? How do you select a square chunk within the matrix, for example, the area (1:2),(0,1)

In [35]:
arr_2d[1:2,0:1]

array([[20]])

nop.

In [36]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [43]:
c

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr = arr[0:5]

In [55]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [57]:
slice_of_arr[:] = 99

In [58]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

It's rows,collumns, so :2 takes rows 0 (the first row) and 1, not including row 2 (the third row) because it's exclusive of the final value. Then it goes onto collumns

In [63]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Returns boolean of True and False values for arr>4

In [67]:
bool_arr = arr>4

In [68]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

Now it only returns arr values where bool_arr is true, similar to creating a raster mask

In [70]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

This method ^ is similar, and you don't have to create a seperate bool_arr value in seperate steps. It is doing the same bool check but within the arr[box]

In [78]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [81]:
len(dice_rolls[dice_rolls>2])

19

This is the fastest way I know to solve the problem of finding the count of dice rolls within dice_rolls over 2, in order to solve the udemy check-in. ^
It wants me to do it in a more tedious way though, so I'm going to do it again vvv

In [84]:
total_rolls_over_two = dice_rolls[dice_rolls > 2]

In [83]:
len(total_rolls_over_two)

19

In [85]:
total_rolls_over_two

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])