In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
 arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Every element in the array is added to 5

In [5]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

These arrays have to be the same size in order for you to be able to add arrays to each other, or subtract, etc

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Note, there is a zero in this array. What happens if you divide arr by arr, i.e. divide by zero?

In [8]:
arr/arr

C:\Users\User\AppData\Local\Temp\ipykernel_420\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

The result is still given, but there is a warning, and the invalid 0/0 cell is given as nan. i.e. non-number

In [9]:
1/0

ZeroDivisionError: division by zero

In normal python ^, this does not give any result

In numpy, a result is given vvv

In [10]:
1/arr

C:\Users\User\AppData\Local\Temp\ipykernel_420\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

The invalid cell is still given as inf (infinity)

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_420\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

a warning is given for the log(0) value

In [14]:
np.mean(arr)

4.5

In [15]:
arr.sum()

45

These functions can be done in two ways:
1. np.mean(arr)     <--- Slightly more tedious method
2. arr.mean()     <--- The coolboy method. Much faster!

In [17]:
arr.mean()

4.5

Same sheit

In [18]:
arr.max()

9

In [19]:
arr.var()

8.25

In [20]:
arr.std()

2.8722813232690143

These calls are being done through numpy, not standard python

In [21]:
arr2d = np.arange(0,25).reshape(5,5)

In [22]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr2d.sum()

300

The sum of 1 + 2 + 3 . . . 23 + 24 + 25 is 300 aparently . . . 

In [24]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

i.e., the sum of each collumn (the sum _across_ the rows) is 50 for collumn 0, 55 for collumn 1, etc. 

In [25]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

arr2d.sum(axis = n)

if n = 0, sum collumns, if n = 1, sum rows

In [27]:
arr2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

Sum of rows ^

In [28]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [29]:
account_total = account_transactions.sum()

In [30]:
account_total

2720