In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mem = np.array([1,2,3])

In [7]:
mem

array([1, 2, 3])

In [8]:
mylist

[1, 2, 3]

In [9]:
myarr = np.array(mylist)

In [10]:
myarr

array([1, 2, 3])

In [12]:
type(myarr)

numpy.ndarray

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

This is now a multi-dimensional matrix. Each comma-seperated bracket [],[],[] contains comma-seperated data.

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Each row is given to a [],[],[] list, and the collumns i.e. the contents of the row are the data contained in the sub-list

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.arrange() is the numpy equavilent to the standard .range() function used in python, but for matrices (presumably . . .)

arange is spelled with one r, not arrange

np.arange(low number - inclusive, high number - noninclusive, step size)

In [20]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

this np.zeros() function produces a 1d vector which is filled in with 0. zeros corresponding to the value of n within np.zeros(n)

These are floats, not ints

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

For whatever stupid reason, this has to be formatted as np.zeros((n,n)) rather than np.zeros(n,n). The later will give an error message. 

This function with the n,n tuple gives an array of 0. zeros

In [25]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

If you know the step size required, use np.arange()

If you know the number of steps required, use np.linspace()


This is not the same as np.arange(), because it takes the total number of values desired as the third paramater, unlike np.arange() which takes the stepsize as the third paramater. 

i.e. 
np.linspace(lower value, upper value, total number of values)

np.arange(lower value, upper value, step size)

Whether you use one or the other depends on whether you know the step size required or the number of steps required


In [32]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

Annoyingly, np.linspace() _includes_ the final number in the series in the syntax, unline np.arrange

i.e. np.linspace(0,10,11) will be evenly spaced integers includinng both *0* and *10*

In [42]:
np.linspace(0,10,11)

11

In [36]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

np.linspace() is short for _linearly spaced_

In [43]:
len(np.linspace(0,10,11))

11

In [49]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Aparently this is commonly used in linear algebra. It produces a square n-sided matrix of 0. with a line of 1. along the diagonal.

In [54]:
np.random.rand(1)

array([0.79384519])

This produces a random number between [0,1) i.e between 0 and 1, where 0 is inclusive and 1 is exclusive

In [56]:
np.random.rand(5,2)

array([[0.5759339 , 0.08465138],
       [0.50353962, 0.08526858],
       [0.13822949, 0.76050501],
       [0.47589133, 0.31688459],
       [0.22364396, 0.96721005]])

This produces a shape with 5 rows and 2 collumns. The range is still [0,1)

In [57]:
np.random.randn(2,2)

array([[ 0.12753766,  2.16292158],
       [-1.93995695, -1.19030121]])

this gives outputs based on a "standard normal" distribution (bell-curve), where the mean is 0 and the range is [-x,x]

Numbers closest to 0 are most likely, extremes near +- x are the least likely

What is the range of this? Not sure . . . 

np.random.randn(rows,collumns)

In [62]:
np.random.randint(0,10)

7

np.random.randint(lower range inclusive, upper range exclusive) draws numbers uniformly, not along normal curve. With no third paramater, it gives 1 output

In [65]:
np.random.randint(0,10,(2,5))

array([[9, 9, 0, 1, 8],
       [1, 8, 4, 7, 8]])

You can set the third paramater to output an array of random numbers

In [67]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

make sure to run these in the same collumn.

In [68]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

You will get the same numbers every time using seed #42, similar to how pi is an irrational number with a definite value

In [69]:
np.random.seed(41)
np.random.rand(4)

array([0.25092362, 0.04609582, 0.67681624, 0.04346949])

In [70]:
arr = np.arange(0,25)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Taking a 1 by 25 vector and turning it into a 5 by 5 array. Note, you cannot use arr.reshape(5,4) etc. because the data cannot be made to fit into that size matrix without changing its values

In [82]:
randarr = np.random.randint(0,11,10)
randarr

array([ 2,  1,  5,  3, 10,  2, 10,  4,  1,  2])

10 random integers from 0 to 10, since 11 is not inclusive

In [87]:
randarr.max()

10

In [85]:
randarr.min()

1

In [88]:
randarr.argmax()

4

Finds the index value corresponding to the max. Remember, 0 is the first index value

In [89]:
randarr.dtype

dtype('int32')

In [102]:
arr.shape

(1, 25)

In [103]:
arr = arr.reshape(5,5)

In [104]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
arr.shape

(5, 5)

In [110]:
myarray = np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])